name: deploy-container
on:
  push:
    branches:
      - master
    paths:
      - "packages/container/**"

defaults:
  run:
    working-directory: package/container

jobs:
  build:
    runs-on: unbunt-latest
    steps:
      - uses: actions/checkout@v2
      - run: nvm use 14
      - run: npm run build
      - run: npm run build
      - run: ls
