name: deploy-container

defaults:
  run:
    working-directory: packages/container

on:
  push:
    branches:
      - master
    paths:
      - "packages/container/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: nvm use 14
      - run: npm run build
      - run: ls
